# Don't print a new line at the start of the prompt
add_newline = true

format = """
[â§](bold yellow)ğŸ¦„ $username\
$hostname\
$directory\
$nodejs\
$git_branch\
$git_commit\
$git_state\
$git_status
[â©](bold yellow)$character"""

[character]
format = "$symbol"
success_symbol = "[âœ”ï¸](bold green) "
error_symbol = "[âœ•](bold red) "
vicmd_symbol = "[Æ](bold cyan) "

[username]
style_root = "red bold"
style_user = "yellow"
