# Don't print a new line at the start of the prompt
add_newline = true

format = """
[⎧](bold yellow)☯︎ $username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status
[⎩](bold yellow)$character"""

[character]
format = "$symbol"
success_symbol = "[✔︎](bold green) "
error_symbol = "[✕](bold red) "
vicmd_symbol = "[Ɲ](bold cyan) "

[username]
style_root = "red bold"
style_user = "yellow"
